#!/usr/bin/env bash
# this is bash script to transfer file to a server using scp
if [[ ! ("$1" || "$2" || "$3") ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking no" -i "$4" "$1" "$3@$2":~/
fi
