#!/usr/bin/env bash
# nginx redirection
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '26 i \     rewrite ^/redirect_me www.google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
