#!/usr/bin/env bash
# nginx redirection to 404

sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '26 i \     rewrite ^/redirect_me www.google.com permanent;location /xyz{ return 404;}error_page 404 /404.html;location = /404.html {root /usr/share/nginx/html;internal;}# Make site accessible from http://localhost/server_name localhost;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo service nginx restart
