#!/usr/bin/bash env
#  listen port 80 with nginx server
sudo rm /etc/nginx/server-enabled/default
ls -s /etc/nginx/server-available/default /etc/nginx/server-enabled/default
sudo /etc/init.d/nginx restart
