#!/usr/bin/env bash
#kill process with filter
#ps axu | grep bash | grep 7-highlander | cut -d " " -f6 | xargs kill
#ps axu | grep bash | grep 7-highlander | cut -d " " -f6 | xargs kill -9
pkill -f "7-highlander"
