#!/usr/bin/env bash
#script that displays numbers from 1 to 100 Displays FizzBuzz when the number is a multiple of 3 and 5 Displays Fizz when the number is multiple of 3 Displays Buzz when the number is a multiple of 5 Otherwise, displays the number In a list format

for e in $(seq 1 100);
do
    if [ $((e % 15)) -eq 0 ]; then
	echo "FizzBuzz"
    elif [ $((e % 3)) -eq 0 ]; then
	echo "Fizz"
    elif [ $((e % 5)) -eq 0 ]; then
	echo "Buzz"
    else
	echo "$e"
    fi
done
