#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=0
while [ $i -lt 8 ]
do
	i=$((i + 1))
	echo "Holberton School"
	if [ $i -eq 8 ]; then
		echo "Hi"
		echo "Holberton School"
	fi
done
