#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=0
while [ $i -lt 10 ]
do
	i=$((i + 1))
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	if [ $i -ne 9 ]; then
		echo "Holberton School"
	fi
done
