#!/usr/bin/env bash
#script that displays The content of the current directory In a list format Where only the part of the name after the first dash is displayed (refer to the example)

#ls | tr " " "\n" | cut -d'-' -f2'
for c in *;
do
	echo "$c" | cut -d'-' -f2
done
